/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/core/layouts/theme_widget.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";

import '../../../shared/auth_frame/auth_frame.dart';
import "../viewmodels/complete_info_viewmodel.dart";
import '../widgets/complete_info_form.dart';

class CompleteInfoMobileScreen extends StatelessWidget {
  const CompleteInfoMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<CompleteInfoViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return AuthFrame(
              image: 'complete-info',
              title: 'complete_your_info'.tr(),
              animationType: AnimationType.fadeInUpRight,
              widget: const CompleteInfoForm(),
              actionText: 'next',
              enabled: viewModel.params.submit,
              action: viewModel.completeInfo,
            );
          },
        );
      },
    );
  }
}
