/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/extensions/assets_extension.dart';
import 'package:tahsaldar/router/app_router.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import "./viewmodels/main_viewmodel.dart";
import '../../resources/colors/colors.dart';
import '../../resources/text_styles/text_styles.dart';
import '../../widgets/animations/animated_gesture.dart';
import '../transactions/transactions_screen.dart';

class MainScreen extends StatefulWidget {
  const MainScreen({Key? key}) : super(key: key);

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> with InstanceState<MainScreen, MainViewModel>, ObserverMixin {
  int index = 0;

  List<Widget> screens = [
    const TransactionsScreen(),
    // const ProfileScreen(),
  ];

  @override
  Widget screen(BuildContext context, viewModel) {
    return BaseScaffold(
      builder: (context, theme) => screens[index],
      // bottomNavigationBar: ClipRRect(
      //   borderRadius: const BorderRadius.only(
      //     topLeft: Radius.circular(20),
      //     topRight: Radius.circular(20),
      //   ),
      //   child: BottomAppBar(
      //     elevation: 10,
      //     notchMargin: 4,
      //     height: 66,
      //     shape: const CircularNotchedRectangle(),
      //     child: Row(
      //       mainAxisAlignment: MainAxisAlignment.spaceAround,
      //       children: <Widget>[
      //         _bottomBarItem('transactions', 0),
      //         _bottomBarItem('profile', 1),
      //       ],
      //     ),
      //   ),
      // ),
      // floatingActionButton: _buildAddIcon(),
    );
  }

  @override
  MainViewModel registerInstance() => MainViewModel();

  _buildAddIcon() {
    return FloatingActionButton(
      splashColor: DesignColors.purple3,
      backgroundColor: DesignColors.primaryColor,
      child: SvgPicture.asset('add-square'.svgAsset, color: Colors.white),
      onPressed: () => appRouter.push( AddPayment()),
    );
  }

  _bottomBarItem(String item, int id) {
    return AnimatedGesture(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          SvgPicture.asset(
            index == id ? item.filledSvgAsset : item.svgAsset,
            color: index == id ? DesignColors.primaryColor : null,
            height: 28,
          ),
          const SizedBox(height: 4),
          Text(item.tr(), style: body3),
        ],
      ),
      callback: () {
        setState(() {
          index = id;
        });
      },
    );
  }
}
