/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// state management for UI
///
/// store and manage your liveData in [ProfileParams].
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:tahsaldar/controllers/auth_controller.dart';
import 'package:tahsaldar/extensions/data_extension.dart';
import 'package:tahsaldar/repositories/payment_repository.dart';
import 'package:tahsaldar/repositories/user_repository.dart';
import 'package:tahsaldar/router/app_router.dart';
import 'package:tahsaldar/viewmodels/base_viewmodel.dart';
import '../../../../extensions/date_extension.dart';
import "profile_params.dart";

class ProfileViewModel extends BaseViewModel {
  final _params = Lazy(() => ProfileParams());
  ProfileParams get params => _params.value;

  final _userRepository = Lazy(() => UserRepository());
  UserRepository get userRepository => _userRepository.value;

  final _paymentRepository = Lazy(() => PaymentRepository());
  PaymentRepository get paymentRepository => _paymentRepository.value;

  @override
  onInit() {
    super.onInit();
    getUser();
    getTotalPaid();
  }

  getUser() {
    callHttpRequest(() => userRepository.getUser(), loading: baseParams.loading, callback: (response) {
      if (response != null) {
        AuthenticationController.saveUser(response);
      }
    });
  }

  getTotalPaid() {
    callHttpRequest(() => paymentRepository.getTotal(month: params.month.value.number, year: params.year.value.toInteger()), loading: baseParams.loading, callback: (response) {
      if (response != null) {
        params.totalPaid.postValue(response);
      }
    });
  }

  logout() async {
    String deviceId = '123'; //TODO
    callHttpRequest(() => userRepository.logout(deviceId), loading: baseParams.loading, callback: (response) async {
      await AuthenticationController.logOut();
      appRouter.replaceAll([const Login()]);
    });
  }
}
