/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
/// 
/// state management for UI
/// 
/// store and manage your liveData in [TransferDetailsParams].
import '../../../../repositories/payment_repository.dart';
import "transfer_details_params.dart";
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:tahsaldar/viewmodels/base_viewmodel.dart';

class TransferDetailsViewModel extends BaseViewModel {
  final _params = Lazy(() => TransferDetailsParams());
  TransferDetailsParams get params => _params.value;

  final _paymentRepository = Lazy(() => PaymentRepository());
  PaymentRepository get paymentRepository => _paymentRepository.value;

  @override
  void onInit() {
    super.onInit();
    getTransactionById();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    super.onDispose();
  }

  double get paymentAmount => params.transfer.value.amount?.toDouble() ?? 0;

  ///Amount as double value
  double get calculateAmount => paymentAmount.toDouble();
  String get amount => paymentAmount.toDouble().toStringAsFixed(0);

  ///Fees as double value
  double get calculateFees =>(params.transfer.value.amount?.toDouble()??0)*0.01;
  String get fees => calculateFees.toStringAsFixed(0);

  ///Total amount as double value
  double get calculateTotalAmount => calculateFees + calculateAmount;
  String get totalAmount => calculateTotalAmount.toStringAsFixed(0);




  getTransactionById() {
    callHttpRequest(
          () => paymentRepository.findOne(params.transfer.value.id.toString()),
      loading: baseParams.loading,
      callback: (response) {
        if (response != null) {
          params.transfer.postValue(response);
        }
      },
    );
  }
  // deleteTransaction(String id) async {
  //   callHttpRequest(
  //         () => paymentRepository.cancel(id),
  //     loading: baseParams.loading,
  //     callback: (response) async {
  //       if (response != null) {
  //         final viewModel=findInstance<TransactionsViewModel>();
  //         final index = viewModel.paginationParams.itemsList.value.items.indexWhere((element) => element.item.id.toString() == id);
  //         viewModel.deleteItem(index);
  //         viewModel.addItemToList(response, index);
  //         viewModel.getTotalPaid();
  //         appRouter.pop();
  //       }
  //     },
  //   );
  // }


}
