import 'package:tahsaldar/extensions/formz_extension.dart';
import 'package:tahsaldar/extensions/live_data_extension.dart';

import '../../../../models/forms/formz_mobile.dart';
import '../../../../models/forms/formz_text.dart';
import '../../../../storage/storage.dart';

/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// declare and manage viewModel-liveData variables.
/// 
/// see: https://pub.dev/packages/flutterx_live_data
/// 
/// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e

class ResetPasswordParams {
  /// mobile text field
  final mobile = const FormzMobile.pure().liveData;
   String phone="" ;

  /// form enabled for submit
  final submit = false.liveData;
  final success = false.liveData;

  /// mobile text field
  final pinCode = ''.liveData;

  /// form enabled for submit

  final resendCodeEnabled = true.liveData;

  final password = const FormzText.pure("").liveData;
  final confirmPassword = const FormzText.pure("").liveData;
  final passwordMatch = true.liveData;




  isFormFilled() {
    return passwordMatch.value&&password.inputValue().isNotEmpty;
  }

}
