/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';



import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import '../../../../core/layouts/base_app_bar.dart';
import '../../../../core/layouts/base_scaffold.dart';
import 'mobile/reset_password_mobile_screen.dart';


import "package:auto_route/auto_route.dart";

class ResetPasswordScreen extends StatefulWidget {
  const ResetPasswordScreen({Key? key}) : super(key: key);

  @override
  State<ResetPasswordScreen> createState() => _ResetPasswordScreenState();
}

class _ResetPasswordScreenState extends State<ResetPasswordScreen> {
  

  @override
  void initState() {
    super.initState();
    
  }
  

  @override
  Widget build(BuildContext context) {
    return BaseScaffold(
      appBar: (context, theme) => baseAppBar(title: "reset_password".tr()),
      builder: (context, theme) =>   const ScreenTypeLayout(mobile: ResetPasswordMobileScreen() ),
          )
        
;
}
}
