import 'package:tahsaldar/models/data_models.dart';

import '../../controllers/auth_controller.dart';

/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
class Env {
  static const localhost = "http://192.168.1.8:3000";
  static const stagingUrl = "https://api-stg.piknclk.com";
  static const liveUrl = "https://api.piknclk.com";
  static const developUrl = "https://tahsildar-back-dev.8byteslab.com";

  static get baseUrl {
    return user.isFake() ? developUrl :  liveUrl;
  }

  static get apiUrl => "$baseUrl/api";
  static get fakeUrl => "$developUrl/api";


  static const excelDownloadLink = '/payment/excel';

  /// pagination
  static const perPage = 15;
}
