/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:tahsaldar/controllers/auth_controller.dart';
import 'package:tahsaldar/events/bus_events.dart';
import 'package:tahsaldar/storage/storage.dart';

import 'env.dart';
import 'logging_interceptor.dart';

/// Config Http Options
Future<void> httpConfig() async {
  await _httpClientConfig();
}

/// Config Http globally
///
/// Add "Authorization" in header to every request sent,
///
/// Add Log on console for see (Request/Response) details.
_httpClientConfig() {
  GetIt.I.registerSingleton<Dio>(Dio()
    ..interceptors.add(
      InterceptorsWrapper(
        onRequest: (request, handler) async {
          var headers = {
            'Accept': 'application/json',
            'format': 'json',
            'Authorization': 'Bearer ${await AuthenticationController.token()}',
            'lang': AppStorage.getLanguage(),
          };
          request.headers.addAll(headers);
          request.connectTimeout = 30000;
          request.receiveTimeout = 30000;
          request.baseUrl = Env.apiUrl;
          handler.next(request);
        },
        onError: (error, handler) {
          if (error.response?.statusCode == 401 || error.response?.statusCode == 403) {
            eventBus.fire(const UnauthorizedEvent());
          }
          handler.next(error);
        },
        onResponse: (response, handler) {
          handler.next(response);
        },
      ),
    )
    ..interceptors.add(LoggingInterceptor()));
}
