/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:tahsaldar/controllers/auth_controller.dart';
import 'package:tahsaldar/events/bus_events.dart';
import 'package:tahsaldar/models/data_models.dart';
import 'package:tahsaldar/storage/storage.dart';

import 'env.dart';
import 'logging_interceptor.dart';

/// Config Http Options
Future<void> httpConfig() async {
  await _httpClientConfig();
}

/// Config Http globally
///
/// Add "Authorization" in header to every request sent,
///
/// Add Log on console for see (Request/Response) details.
_httpClientConfig() {
  List<String> unAuthRequestsList = ["/login" ,"/login-password",
    '/reset-password-request','reset-password-verification','/verify-code'];
  GetIt.I.registerSingleton<Dio>(Dio()
    ..interceptors.add(
      InterceptorsWrapper(
        onRequest: (request, handler) async {
          PackageInfo packageInfo = await PackageInfo.fromPlatform();

          var headers = {
            'Accept': 'application/json',
            'format': 'json',
            'Authorization': 'Bearer ${await AuthenticationController.token()}',
            'lang': AppStorage.getLanguage(),
            'version':"${Platform.isAndroid ? "android" : "ios"}_${packageInfo.version}"
          };
          request.headers.addAll(headers);
          request.connectTimeout = 30000;
          request.receiveTimeout = 30000;
          if (user.isFake() || (
              (unAuthRequestsList.contains(request.path)) && !(request.data['phone'] as String ).startsWith("+9639"))
          ){
            request.baseUrl = Env.fakeUrl;
          } else {
            request.baseUrl = Env.apiUrl;
          }

          handler.next(request);
        },
        onError: (error, handler) {


          if (error.response?.statusCode == 403 && error.response?.data is Map && error.response?.data['code'] == 'old_version'){
            print("hi");
            eventBus.fire( OutdatedVersionEvent(error.response?.data['message'] ?? "يرجى تحديث التطبيق"));

          }
          else if (error.response?.statusCode == 401 || error.response?.statusCode == 403) {
            
              eventBus.fire(const UnauthorizedEvent());
            }
          handler.next(error);
        },
        onResponse: (response, handler) {
          handler.next(response);
        },
      ),
    )
    ..interceptors.add(LoggingInterceptor()));
}
