/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:tahsaldar/models/responses/list_response/list_response.dart';
import 'package:tahsaldar/network/config/env.dart';
import 'package:tahsaldar/models/data_models.dart';
import 'package:tahsaldar/models/responses/base_response/base_response.dart';
part 'notification_rest_client.g.dart';

@RestApi()
abstract class NotificationRestClient {
  factory NotificationRestClient(Dio dio) = _NotificationRestClient;

  @GET("/notification")
  Future<BaseResponse<ListResponse<Notification>>> findAll({
    @Query("page") required int page,
    @Query("per_page") int perPage = Env.perPage,
    @Query("search") String? query,
    @CancelRequest() CancelToken? cancelToken,
  });

  @GET("/notification/{id}")
  Future<BaseResponse<Notification>> findOne({
    @Path("id") required String id,
    @CancelRequest() CancelToken? cancelToken,
  });
}
