/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';






import "package:auto_route/auto_route.dart";
import 'package:tahsaldar/ui/screens/change_password/viewmodels/chaneg_password_viewmodel.dart';
import 'package:tahsaldar/ui/screens/change_password/widgets/change_password_form.dart';

import '../../../core/layouts/theme_widget.dart';
import '../../../shared/auth_frame/auth_frame.dart';
import '../../../widgets/instance/instance_builder.dart';

class ChangePasswordMobileScreen extends StatefulWidget {
  const ChangePasswordMobileScreen({Key? key}) : super(key: key);

  @override
  State<ChangePasswordMobileScreen> createState() => _ChangePasswordMobileScreenState();
}

class _ChangePasswordMobileScreenState extends State<ChangePasswordMobileScreen> {
  final formKey=GlobalKey<FormState>();



  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ChangePasswordViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return AuthFrame(
              image: "finger-print",
              title: 'change_password_info'.tr(),
              animationType: AnimationType.fadeInUpRight,
              widget: Form(key:formKey
                  ,child: const ChangePasswordForm()),
              actionText: 'next',
              enabled: viewModel.params.submit,
              action:() {
                if(formKey.currentState!.validate()){
                  viewModel.changePassword();

                }
              },
            );
          },
        );
      },
    );
}
}
