/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';






import "package:auto_route/auto_route.dart";
import 'package:tahsaldar/extensions/formz_extension.dart';
import 'package:tahsaldar/ui/screens/reset_password_request/viewmodels/reset_password_viewmodel.dart';

import '../../../../../core/layouts/theme_widget.dart';
import '../../../../../shared/auth_frame/auth_frame.dart';
import '../../../../../widgets/instance/instance_builder.dart';
import '../../../../../widgets/loaders/live_data_loader.dart';
import '../widgets/verify_code_reset_form.dart';

class ResetPasswordVerificationMobileScreen extends StatefulWidget {
  const ResetPasswordVerificationMobileScreen({Key? key}) : super(key: key);

  @override
  State<ResetPasswordVerificationMobileScreen> createState() => _ResetPasswordVerificationMobileScreenState();
}

class _ResetPasswordVerificationMobileScreenState extends State<ResetPasswordVerificationMobileScreen> {
  

  @override
  void initState() {
    super.initState();
    
  }
  

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ResetPasswordViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return Stack(
              children: [
                AuthFrame(
                  image: 'verify-code',
                  animationType: AnimationType.fadeInRight,
                  title: 'enter_your_code'.tr(),
                  body: '${'we_sent_you_the_code'.tr()} ${viewModel.params.phone.replaceFirst("+963", "0")}',
                  widget: const VerifyCodeResetForm(),
                  actionText: 'next',
                  enabled: viewModel.params.submit,
                  action: viewModel.verifyCode,
                ),
                LoadingListenerWidget(loading: viewModel.baseParams.loading),
              ],
            );
          },
        );
      },
    );

}
}
