/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/router/app_router.dart';
import 'package:tahsaldar/ui/core/layouts/base_app_bar.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import 'package:tahsaldar/ui/widgets/clickable_svg/clickable_svg.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import "./viewmodels/profile_viewmodel.dart";
import 'mobile/profile_mobile_screen.dart';

class ProfileScreen extends StatefulWidget {
  const ProfileScreen({Key? key}) : super(key: key);

  @override
  State<ProfileScreen> createState() => _ProfileScreenState();
}

class _ProfileScreenState extends State<ProfileScreen> with InstanceState<ProfileScreen, ProfileViewModel>, ObserverMixin {
  @override
  void observeLiveData(lifeCycle, viewModel) {
    // register observers...
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(
            title: 'profile'.tr(),
            actions: [
              ClickableSvg(
                svg: 'edit',
                callback: () => appRouter.push(const UpdateProfile()),
              ),
            ],
          ),
          builder: (context, theme) => const ScreenTypeLayout(
            mobile: ProfileMobileScreen(),
          ),
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  ProfileViewModel registerInstance() => ProfileViewModel();
}
