/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_app_bar.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import "./viewmodels/transfers_viewmodel.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import 'mobile/transfers_mobile_screen.dart';


import "package:auto_route/auto_route.dart";
class TransfersScreen extends StatefulWidget {
  const TransfersScreen({Key? key}) : super(key: key);

  @override
  State<TransfersScreen> createState() => _TransfersScreenState();
}

class _TransfersScreenState extends State<TransfersScreen> with InstanceState<TransfersScreen, TransfersViewModel>, ObserverMixin {
  @override
  Widget screen(context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(title: 'last_transfer'.tr()),
          builder: (context, theme) =>   const ScreenTypeLayout(mobile: TransfersMobileScreen() ),
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  TransfersViewModel registerInstance() => TransfersViewModel();
}
