/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/core/layouts/theme_widget.dart';
import 'package:tahsaldar/ui/screens/update_profile/widgets/update_profile_form.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";

import '../../../core/layouts/base_layout.dart';
import "../viewmodels/update_profile_viewmodel.dart";

class UpdateProfileMobileScreen extends StatelessWidget {
  const UpdateProfileMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<UpdateProfileViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return const BaseLayout(
              child: UpdateProfileForm(),
            );
          },
        );
      },
    );
  }
}
