/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import "package:easy_localization/easy_localization.dart";
import 'package:flutter/material.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";
import "../../../core/layouts/theme_widget.dart";
import "../../../shared/auth_frame/auth_frame.dart";
import "../viewmodels/reset_password_viewmodel.dart";
import "../widgets/login_reset_form.dart";


class ResetPasswordRequestMobileScreen extends StatelessWidget {
  const ResetPasswordRequestMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ResetPasswordViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return AuthFrame(
              image: 'login',
              animationType: AnimationType.roulette,
              title: 'enter_the_same_mobile_number'.tr(),
              body: 'you_will_receive_otp'.tr(),
              widget: const LoginResetForm(),
              actionText: 'next',
              enabled: viewModel.params.success,
              action: viewModel.resetPasswordRequest,
            );
          },
        );
      },
    );
  }
}
