import 'package:tahsaldar/extensions/live_data_extension.dart';
import 'package:tahsaldar/storage/storage.dart';

/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// declare and manage viewModel-liveData variables.
///
/// see: https://pub.dev/packages/flutterx_live_data
///
/// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e

class VerifyCodeParams {
  ///
  String mobile = '';

  /// mobile text field
  final pinCode = ''.liveData;

  /// form enabled for submit
  final submit = false.liveData;

  final resendCodeEnabled = true.liveData;

  VerifyCodeParams() {
    final dateTime = AppStorage.getResendCodeDatetime() ?? DateTime.now();
    if (!DateTime.now().subtract(const Duration(minutes: 2)).isBefore(dateTime)) {
      AppStorage.setResendCodeDatetime(DateTime.now());
    }
    resendCodeEnabled.postValue(false);
  }
}
