/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// state management for UI
///
/// store and manage your liveData in [VerifyCodeParams].
import 'package:easy_localization/easy_localization.dart';
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:tahsaldar/controllers/auth_controller.dart';
import 'package:tahsaldar/events/bus_events.dart';
import 'package:tahsaldar/models/ui_models/ui_message.dart';
import 'package:tahsaldar/storage/storage.dart';
import 'package:tahsaldar/viewmodels/base_viewmodel.dart';
import 'package:tahsaldar/repositories/user_repository.dart';
import 'package:tahsaldar/router/app_router.dart';
import "verify_code_params.dart";

class VerifyCodeViewModel extends BaseViewModel {
  final _params = Lazy(() => VerifyCodeParams());
  VerifyCodeParams get params => _params.value;

  final _userRepository = Lazy(() => UserRepository());
  UserRepository get userRepository => _userRepository.value;

  onPinChanged(String pinCode) {
    if (pinCode.length == 4) {
      params.pinCode.postValue(pinCode);
      params.submit.postValue(true);
      // hide soft keyboard
      eventBus.fire(const SoftKeyboardEvent());
      verifyCode();
    } else {
      params.submit.postValue(false);
    }
  }

  resendCode() {
    callHttpRequest(
      () => userRepository.login(params.mobile),
      loading: baseParams.loading,
      onSuccess: (success) {
        if (success) {
          baseParams.uiMessage.postValue(UiMessage(message: "code_resent".tr(), state: UiMessageState.success));
          params.resendCodeEnabled.postValue(false);
          AppStorage.setResendCodeDatetime(DateTime.now());
        }
      },
    );
  }

  verifyCode() {
    String mobile = params.mobile;
    String pinCode = params.pinCode.value;
    callHttpRequest(
      () => userRepository.verifyCode(mobile, pinCode),
      loading: baseParams.loading,
      callback: (response) async {
        if (response != null && response.user != null) {
          await AuthenticationController.login(response.user!);
          if (response.user!.fullName == null) {
            appRouter.push(const CompleteInfo());
          } else {
            appRouter.replaceAll([const Main()]);
          }
        }
      },
    );
  }

  DateTime enabledDatetime() {
    final datetime = AppStorage.getResendCodeDatetime() ?? DateTime.now();
    return datetime.add(const Duration(minutes: 2));
  }
}
