/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tahsaldar/extensions/data_extension.dart';
import 'package:tahsaldar/models/data/city/city.dart';

import '../bank/bank.dart';
import '../media_item/media_item.dart';

part 'user.freezed.dart';
part 'user.g.dart';

// ----------(json)----------
/*
{
            "id": 1,
            "full_name": "3123123",
            "active": 1,
            "phone": "+963993522958",
            "bank_id": 2,
            "bank_account_number": "123",
            "remember_token": null,
            "created_at": "2023-02-19T07:55:47.000000Z",
            "updated_at": "2023-02-19T08:53:29.000000Z",
            "access_token": "11|qSnQYaJLrMEi47qExqoJMmORs30UI5ZkfoIQvzsC",
            "bank": {
                "id": 2,
                "created_at": "2023-02-19T08:45:06.000000Z",
                "updated_at": "2023-02-19T08:45:06.000000Z",
                "name": "al baraka"
            }
        }
*/
// --------------------------

@freezed
class User with _$User {
  const factory User({
    dynamic id,
    String? fullName,
    dynamic active,
    dynamic phone,
    dynamic bankId,
    dynamic bankAccountNumber,
    dynamic rememberToken,
    String? createdAt,
    String? updatedAt,
    String? accessToken,
    Bank? bank,
    List<MediaItem>? media,
    dynamic cityId,
    City? city,
    String? email,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);


}

extension UserUtils on User {
  bool userHasMedia() => media != null && media!.isNotEmpty && media![0].originalUrl != null && media![0].id != null;

  int? mediaId() => userHasMedia() ? media![0].id.toString().toInteger() : null;

  String? imageUrl() => userHasMedia() ? media![0].originalUrl : null;
  bool  isFake () {
    if (phone == null || (phone as String).isEmpty || (phone as String).startsWith("+9639")){
      return false;
    }
    return true;
  }

  String bankName (){
    if (isFake()){
      if (bankId == 21) return "ADIB".tr();
      return "MASREQ NEO".tr();
    }
    return bank?.name ?? "";
  }
  String cityName (){
    if (isFake()){
      if (cityId == 2) return "Abu Dhabi".tr();
      return "Dubai".tr();
    }
    return city?.name ?? "";
  }
}
