/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';

part 'media_item.freezed.dart';
part 'media_item.g.dart';

// ----------(json)----------
/*
  {
                "id": 1,
                "model_type": "App\\Models\\User",
                "model_id": 1,
                "uuid": "b5c44893-8ed2-4f94-b7d1-bf86f8e97c95",
                "collection_name": "default",
                "name": "country-bank2",
                "file_name": "country-bank2.png",
                "mime_type": "image/png",
                "disk": "public",
                "conversions_disk": "public",
                "size": 15287,
                "manipulations": [],
                "custom_properties": [],
                "generated_conversions": [],
                "responsive_images": [],
                "order_column": 1,
                "created_at": "2023-02-28T11:38:58.000000Z",
                "updated_at": "2023-02-28T11:42:26.000000Z",
                "original_url": "http://tahsldar-server.test/storage/1/country-bank2.png",
                "preview_url": ""
            }
*/
// --------------------------

@freezed
class MediaItem with _$MediaItem {
  const factory MediaItem({
    dynamic id,
    String? name,
    String? originalUrl,
    @JsonKey(name: 'mime_type') String? mimeType,
    @JsonKey(name: 'collection_name') String? collectionName,
  }) = _MediaItem;

  factory MediaItem.fromJson(Map<String, dynamic> json) => _$MediaItemFromJson(json);
}
