/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import "./viewmodels/transactions_viewmodel.dart";
import 'mobile/transactions_mobile_screen.dart';

class TransactionsScreen extends StatefulWidget {
  const TransactionsScreen({Key? key}) : super(key: key);

  @override
  State<TransactionsScreen> createState() => _TransactionsScreenState();
}

class _TransactionsScreenState extends State<TransactionsScreen> with InstanceState<TransactionsScreen, TransactionsViewModel>, ObserverMixin {
  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        const ScreenTypeLayout(mobile: TransactionsMobileScreen()),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  TransactionsViewModel registerInstance() => TransactionsViewModel();
}
