/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import 'package:tahsaldar/ui/screens/change_password/viewmodels/chaneg_password_viewmodel.dart';
import '../../core/layouts/base_app_bar.dart';
import '../../core/layouts/base_scaffold.dart';
import '../../widgets/instance/instance_state.dart';
import '../../widgets/loaders/live_data_loader.dart';
import 'mobile/change_password_mobile_screen.dart';

class ChangePasswordScreen extends StatefulWidget {
  const ChangePasswordScreen({Key? key}) : super(key: key);

  @override
  State<ChangePasswordScreen> createState() => _ChangePasswordScreenState();
}

class _ChangePasswordScreenState extends State<ChangePasswordScreen> with InstanceState<ChangePasswordScreen, ChangePasswordViewModel>, ObserverMixin {


  @override
  Widget screen(BuildContext context, ChangePasswordViewModel viewModel) {
    return  Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(title: "change_password".tr()),
          builder:  (context, theme) =>   const ScreenTypeLayout(mobile: ChangePasswordMobileScreen() ),
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),

      ],
    );
  }

  @override
  ChangePasswordViewModel registerInstance() => ChangePasswordViewModel();
}
