/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tahsaldar/network/config/env.dart';
part 'customer.freezed.dart';
part 'customer.g.dart';


// ----------(json)----------
/*
{
         "id": 2,
          "name": "test",
          "phone": "991781549",
          "bank_account_number": null,
          "bank_id": null,
          "created_at": "2023-12-04T11:41:27.000000Z",
          "updated_at": "2023-12-04T11:41:27.000000Z"
}
*/
// --------------------------

@freezed
class Customer with _$Customer {
  const factory Customer({
    int? id,
    String? name,
    String? phone,
    String? bankAccountNumber,
    int? bankId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) = _Customer;

  factory Customer.fromJson(Map<String, dynamic> json) =>
      _$CustomerFromJson(json);
}

