/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// state management for UI
///
/// store and manage your liveData in [LoginParams].
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:tahsaldar/extensions/formz_extension.dart';
import 'package:tahsaldar/models/forms/formz_mobile.dart';
import 'package:tahsaldar/viewmodels/base_viewmodel.dart';

import 'package:tahsaldar/events/bus_events.dart';
import 'package:tahsaldar/repositories/user_repository.dart';
import 'package:tahsaldar/router/app_router.dart';
import "login_params.dart";

class LoginViewModel extends BaseViewModel {
  final _params = Lazy(() => LoginParams());
  LoginParams get params => _params.value;

  final _userRepository = Lazy(() => UserRepository());
  UserRepository get userRepository => _userRepository.value;

  canLogin() => params.mobile.inputValue().isNotEmpty;

  /// check if phone number is valid
  void attrChanged(MutableLiveData<FormzMobile> attr, String value) {
    final newValue = FormzMobile.dirty(value);
    attr.postValue(newValue);
    if (attr.value.valid) {
      // hide soft keyboard
      eventBus.fire(const SoftKeyboardEvent());
    }
    params.submit.postValue(attr.value.valid);
    params.success.postValue(params.submit.value);

  }

  login() {
    String mobile = params.mobile.inputValue().trim();
    if (mobile.startsWith("0")) {
      mobile = mobile.replaceFirst("0", "");
    }
    mobile = "+963$mobile";
    callHttpRequest(() => userRepository.login(mobile,false), loading: baseParams.loading, callback: (response) {
      if(response!=null){
        if(response){
          appRouter.push(LoginPassword(mobile: mobile));

        }else{

              appRouter.push(VerifyCode(mobile: mobile));


        }
      }

    });
  }



}
