/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/core/layouts/theme_widget.dart';
import 'package:tahsaldar/ui/resources/dimensions/dimensions.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";

import "../viewmodels/add_payment_viewmodel.dart";
import '../widgets/add_payment_form.dart';

class AddPaymentMobileScreen extends StatelessWidget {
  const AddPaymentMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<AddPaymentViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return const Padding(
              padding: EdgeInsets.only(top: spaceBelowAppBar),
              child: AddPaymentForm(),
            );
          },
        );
      },
    );
  }
}
