/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import '../../../controllers/auth_controller.dart';
import '../../../router/app_router.dart';
import "./viewmodels/initial_viewmodel.dart";
import 'mobile/initial_mobile_screen.dart';

class InitialScreen extends StatefulWidget {
  const InitialScreen({Key? key}) : super(key: key);

  @override
  State<InitialScreen> createState() => _InitialScreenState();
}

class _InitialScreenState extends State<InitialScreen> with InstanceState<InitialScreen, InitialViewModel>, ObserverMixin {
  @override
  void onInitState(InitialViewModel instance) {
    _handleNavigation();
    super.onInitState(instance);
  }

  _handleNavigation() async {
    bool isLoggedIn = await AuthenticationController.loggedIn();
    bool isCompleteProfile = await AuthenticationController.completeProfile();
    Future.delayed(const Duration(seconds: 1), () {

      appRouter.replaceAll([isLoggedIn ?isCompleteProfile? const Main():const CompleteInfo() : const Login()]);
    });
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return const Scaffold();
  }

  @override
  InitialViewModel registerInstance() => InitialViewModel();
}
