import 'package:tahsaldar/controllers/auth_controller.dart';
import 'package:tahsaldar/extensions/formz_extension.dart';
import 'package:tahsaldar/extensions/live_data_extension.dart';
import 'package:tahsaldar/ui/widgets/autocomplete_text_form_field/autocomplete_item_model.dart';

import '../../../../models/forms/formz_text.dart';

/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// declare and manage viewModel-liveData variables.
///
/// see: https://pub.dev/packages/flutterx_live_data
///
/// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e

class CompleteInfoParams {
  /// full name field
  final fullName = const FormzText.pure().liveData;

  /// User bank
  final bankId = const FormzText.pure("").liveData;
  final bankName = const FormzText.pure("").liveData;

  final banks = <AutoCompleteItemModel>[].liveData;

  /// User bank account number
  final bankAccountNumber = const FormzText.pure("").liveData;

  /// Confirm user bank account number
  final confirmBankAccountNumber = const FormzText.pure("").liveData;

  final bankAccountMatch = true.liveData;

  final password = const FormzText.pure("").liveData;
  final confirmPassword = const FormzText.pure("").liveData;
  final passwordMatch = true.liveData;


  final addresses = <AutoCompleteItemModel>[].liveData;

  /// User address
  final addressId = FormzText.pure(userLiveData.value.cityId?.toString() ?? "").liveData;
  final addressName = FormzText.pure(userLiveData.value.city?.name ?? "").liveData;

  /// form enabled for submit
  final submit = false.liveData;

  isFormFilled() {
    return fullName.inputValue().isNotEmpty &&
        bankId.inputValue().isNotEmpty &&
        bankAccountNumber.inputValue().isNotEmpty &&
        bankAccountMatch.value &&
        addressId.inputValue().isNotEmpty&&passwordMatch.value&&password.inputValue().isNotEmpty;
  }
}
