/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:tahsaldar/models/data_models.dart';
import 'package:tahsaldar/models/responses/base_response/base_response.dart';
import 'package:tahsaldar/network/config/env.dart';

part 'bank_rest_client.g.dart';

@RestApi()
abstract class BankRestClient {
  factory BankRestClient(Dio dio) = _BankRestClient;

  @POST("/bank")
  Future<BaseResponse<Bank>> create({
    @Body() required Bank bank,
    @CancelRequest() CancelToken? cancelToken,
  });

  @PUT("/bank/{id}")
  Future<BaseResponse<Bank>> update({
    @Path("id") required String id,
    @Body() required Bank bank,
    @CancelRequest() CancelToken? cancelToken,
  });

  @GET("/bank")
  Future<BaseResponse<List<Bank>>> findAll({
    @Query("page") required int page,
    @Query("per_page") int perPage = Env.perPage,
    @Query("search") String? query,
    @Query("isPaginate") bool? isPaginate,
    @CancelRequest() CancelToken? cancelToken,
  });

  @GET("/bank/{id}")
  Future<BaseResponse<Bank>> findOne({
    @Path("id") required String id,
    @CancelRequest() CancelToken? cancelToken,
  });

  @DELETE("/bank/{id}")
  Future<BaseResponse<dynamic>> delete({
    @Path("id") required String id,
    @CancelRequest() CancelToken? cancelToken,
  });
}
