/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart' hide Notification;
import 'package:tahsaldar/models/data_models.dart';
import 'package:tahsaldar/ui/resources/dimensions/dimensions.dart';
import 'package:tahsaldar/ui/screens/notifications/widgets/notifications_list.dart';
import 'package:tahsaldar/ui/widgets/infinite_scroll_view/infinite_scroll_view.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";

import "../viewmodels/notifications_viewmodel.dart";

class NotificationsMobileScreen extends StatelessWidget {
  const NotificationsMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<NotificationsViewModel>(
      builder: (viewModel) {
        return Padding(
          padding: const EdgeInsets.only(top: spaceBelowAppBar),
          child: InfiniteScrollView<NotificationsViewModel, Notification>(
            viewModel: viewModel,
            child: (list) => NotificationListWidget(notifications: list),
          ),
        );
      },
    );
  }
}
