/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import "./viewmodels/login_password_viewmodel.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import 'mobile/login_password_mobile_screen.dart';

import "package:auto_route/auto_route.dart";

class LoginPasswordScreen extends StatefulWidget {
  final String mobile;

  const LoginPasswordScreen({Key? key, required this.mobile}) : super(key: key);

  @override
  State<LoginPasswordScreen> createState() => _LoginPasswordScreenState();
}

class _LoginPasswordScreenState extends State<LoginPasswordScreen>
    with
        InstanceState<LoginPasswordScreen, LoginPasswordViewModel>,
        ObserverMixin {
  @override
  void onInitState(LoginPasswordViewModel instance) {
    instance.params.mobile = widget.mobile;
    super.onInitState(instance);
  }

  @override
  Widget screen(context, viewModel) {
    return Stack(
      children: [
        const Scaffold(
          body: ScreenTypeLayout(mobile: LoginPasswordMobileScreen()),
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  LoginPasswordViewModel registerInstance() => LoginPasswordViewModel();
}
