/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:formz/formz.dart';

import '../models/forms/formz_text.dart';

extension LiveDataInputUtils on LiveData<FormzInput> {
  bool isNotEmpty() {
    return value.value.isNotEmpty;
  }

  String inputValue() {
    return value.value;
  }
}

void attrChanged(MutableLiveData<FormzText> attr, String value) {
  final newValue = FormzText.dirty(value);
  attr.postValue(newValue);
}
