import 'package:tahsaldar/extensions/formz_extension.dart';
import 'package:tahsaldar/extensions/live_data_extension.dart';
import 'package:tahsaldar/router/app_router.dart';

import '../../../../models/data/transfer/transfer.dart';
import '../../../../models/forms/formz_mobile.dart';
import '../../../../models/forms/formz_text.dart';
import '../../../widgets/autocomplete_text_form_field/autocomplete_item_model.dart';

/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// declare and manage viewModel-liveData variables.
/// 
/// see: https://pub.dev/packages/flutterx_live_data
/// 
/// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e

class AddTransferParams {
  final bankId = const FormzText.pure("").liveData;
  final banks = <AutoCompleteItemModel>[].liveData;
  final bankName = const FormzText.pure("").liveData;
  final name = const FormzText.pure("").liveData;
  final phone = const FormzMobile.pure().liveData;
  final amount = const FormzText.pure("").liveData;
  final bankAccountNumber = const FormzText.pure("").liveData;
  final confirmBankAccountNumber = const FormzText.pure("").liveData;

  final submit = false.liveData;

  late Transfer transfer;
  final bankAccountMatch = true.liveData;

  isFormFilled() {
    return name.inputValue().isNotEmpty&&phone.value.valid && amount.inputValue().isNotEmpty&&bankId.inputValue().isNotEmpty &&
        bankAccountMatch.value &&
        bankAccountNumber.inputValue().isNotEmpty;
  }

}
