<?php

namespace App\Repositories\Eloquent;

use App\Definitions\PaymentStatus;
use App\Definitions\PaymentTypeEnums;
use App\Models\BaseModel;
use App\Repositories\PaymentRepositoryInterface;
use App\Models\Payment;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PaymentRepository extends BaseRepository implements PaymentRepositoryInterface
{
    /**
     * PaymentRepository constructor.
     * @param Payment $model
     * @param SettingRepository $settingRepository
     */
    public function __construct(Payment $model,private SettingRepository $settingRepository)
    {
        parent::__construct($model);
    }

    /**
     * @param null $user_id
     * @param $data
     * @param $status
     * @return array
     */
    public function getSumAmountByStatus($user_id ,$data,$status): array
    {
        $query = $this->model->where('status', $status)
            ->where('type', $data['type'])
            ->whereYear('created_at', $data['year'])
            ->whereMonth('created_at', $data['month']);
        if ($user_id)
        {
            $query->where('user_id',$user_id);
        }
        $total_amount =  $query->sum('amount');

        return ['total_amount' => $total_amount];
    }

    public function getStatics($date)
    {
        $query = $this->model->query();
        if(!empty($date['userId'])){
            $query->where('user_id',$date['userId']);
        }
        if (!empty($date['from_date'])) {
            $fromDate = Carbon::createFromFormat('Y-m-d', $date['from_date'])->startOfDay()->format('Y-m-d H:i:s');
            $query->whereDate('created_at','>=',$fromDate);
        }
        if (!empty($date['to_date'])) {
            $toDate = Carbon::createFromFormat('Y-m-d', $date['to_date'])->endOfDay()->format('Y-m-d H:i:s');
            $query->whereDate('created_at','<=',$toDate);
        }
        $data['total_transactions'] = $query->count();
        $unsuccessful_transactions = clone $query;
        $data['unsuccessful_transactions'] = $unsuccessful_transactions->whereIn('status',[PaymentStatus::CANCELLED,PaymentStatus::REFUNDED])->count();
        $paid_value = clone $query;
        $data['paid_value'] = $paid_value->where('status', PaymentStatus::PAID)->sum('amount');
        $data['pending_value'] = $query->where('status', PaymentStatus::PENDING)->sum('amount');
        return $data;
    }

    public function getMerchantPaymentsAsCustomer($data)
    {
        $query = Payment::join('customers','payments.customer_id','customers.id')
        ->where('customers.phone',$data['phone'])
        ->where('payments.status',$data['status'])
        ->select('payments.*');
        
        return $query->get();
    }

    public function getExpired(): Collection|array
    {
        return $this->model->query()
            ->where('status',PaymentStatus::PENDING)
            ->where('expiry_date','<',date("Y-m-d H:i:s"))
            ->get('id');
    }

    public function getScheduled(): Collection|array
    {
        return $this->model->query()->with('user')
            ->where('status',PaymentStatus::SCHEDULED)
            ->where('scheduled_date','<',date("Y-m-d H:i:s"))
            ->get();
    }

    public function create(array $payload): ?BaseModel
    {
        $fees = $this->settingRepository->getElementBy('key','fees_percentage');
        if ($fees)
            $fees_percentage = $fees->value;
        else
            $fees_percentage = 10;

        if ($payload['type'] == PaymentTypeEnums::TRANSFER)
            $fees_percentage = 1;
        $payload['uuid'] = Str::uuid()->toString();
        $payload['fees_percentage'] = $fees_percentage;
        $payload['fees_value'] = ($payload['amount'] * $fees_percentage) / 100;
        return parent::create($payload);
    }

    public function update(int $modelId, array $payload, array $option = [])
    {
        if (isset($payload['amount'])){
            $fees = $this->settingRepository->getElementBy('key','fees_percentage');
            $model = $this->model->findOrFail($modelId);
            if ($model->type == PaymentTypeEnums::TRANSFER)
                $fees_percentage = 1;
            else
                $fees_percentage = $model->fees_percentage ?? $fees;
            $payload['fees_percentage'] = $fees_percentage;
            $payload['fees_value'] = ($payload['amount'] * $fees_percentage) / 100;
        }
        return parent::update($modelId, $payload, $option); // TODO: Change the autogenerated stub
    }

    public function getLineChart($start, $end,$user_id = null): array
    {
        $group_by = [
            'day' => 'DAY(created_at) as date',
            'month' => 'MONTH(created_at) as date',
            'year' => 'YEAR(created_at) as date'
        ];
        $datesResult = generateDateRange($start, $end);
        $ranges = $datesResult['range'];
        $per = $datesResult['per'];

        $query =  $this->model->query()
            ->select(
                DB::raw($group_by[$per]),
                DB::raw('count(*) as count'),
                DB::raw('sum(amount) as total'),
            )
            ->where('status',PaymentStatus::PAID)
            ->whereDate('created_at','>=',$start)
            ->whereDate('created_at','<=',$end);

        if ($user_id) $query->where('user_id', $user_id);

        $query = $query
            ->groupBy('date')
            ->get();


        $countData = [];
        $totalData = [];
        foreach ($ranges as $element) {
            $sameDateIndex = null;
            foreach ($query as $key => $item) {
                if ($item->date == $element) {
                    $sameDateIndex = $key;
                }
            }
            $countData[] = ["name" => $element, "value" => !is_null($sameDateIndex) ? $query[$sameDateIndex]->count : 0];
            $totalData[] = ["name" => $element, "value" => !is_null($sameDateIndex) ? $query[$sameDateIndex]->total : 0];
        }
        return ['totalData' => $totalData, 'countData' => $countData];
    }


}
