/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:tahsaldar/models/data_models.dart';
import 'package:tahsaldar/models/responses/base_response/base_response.dart';
import 'package:tahsaldar/network/config/env.dart';

import '../../models/data/transfer/transfer.dart';
import '../../models/responses/list_response/list_response.dart';

part 'transfer_rest_client.g.dart';

@RestApi()
abstract class TransferRestClient {
  factory TransferRestClient(Dio dio) = _TransferRestClient;

  @POST("/transfer/create-payment")
  Future<BaseResponse<int>> createTransfer({
    @Body() required Transfer transfer,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST("/transfer/execute-payment")
  Future<BaseResponse<dynamic>> executeTransfer({
    @Field("payment_id") required int paymentId,
    @CancelRequest() CancelToken? cancelToken,
  });
}
