/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_app_bar.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import '../../../models/data/payment/payment.dart';
import "./viewmodels/add_payment_viewmodel.dart";
import 'mobile/add_payment_mobile_screen.dart';

class AddPaymentScreen extends StatefulWidget {
  bool isUpdate;
  Payment? payment;
   AddPaymentScreen({Key? key,this.isUpdate=false,this.payment}) : super(key: key);

  @override
  State<AddPaymentScreen> createState() => _AddPaymentScreenState();
}

class _AddPaymentScreenState extends State<AddPaymentScreen> with InstanceState<AddPaymentScreen, AddPaymentViewModel>, ObserverMixin {
  @override
  void observeLiveData(observer, viewModel) {
    viewModel.params.isUpdate=widget.isUpdate;
    if(widget.isUpdate&&widget.payment!=null){
      viewModel.convertModelToField(widget.payment!);
    }

    // register observers...
  }
@override
  void initState() {
    // TODO: implement initState
    super.initState();
  }
  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(title:widget.isUpdate?"update_payment_request".tr(): 'add_payment_request'.tr()),
          builder: (context, theme) {
            return const ScreenTypeLayout(mobile: AddPaymentMobileScreen());
          },
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  AddPaymentViewModel registerInstance() => AddPaymentViewModel();
}
