/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';

import '../../data_models.dart';

part 'login_response.freezed.dart';
part 'login_response.g.dart';

// ----------(json)----------
/*
{
   "user": {
            "id": 1,
            "full_name": "3123123",
            "active": 1,
            "phone": "+963993522958",
            "bank_id": 2,
            "bank_account_number": "123",
            "remember_token": null,
            "created_at": "2023-02-19T07:55:47.000000Z",
            "updated_at": "2023-02-19T08:53:29.000000Z",
            "access_token": "11|qSnQYaJLrMEi47qExqoJMmORs30UI5ZkfoIQvzsC",
            "bank": {
                "id": 2,
                "created_at": "2023-02-19T08:45:06.000000Z",
                "updated_at": "2023-02-19T08:45:06.000000Z",
                "name": "al baraka"
            }
        }
}
*/
// --------------------------

@freezed
class LoginResponse with _$LoginResponse {
  const factory LoginResponse({
    User? user,
  }) = _LoginResponse;

  factory LoginResponse.fromJson(Map<String, dynamic> json) => _$LoginResponseFromJson(json);
}
