/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/screens/reset_password_request/viewmodels/reset_password_viewmodel.dart';
import '../../../../../core/layouts/theme_widget.dart';
import '../../../../../shared/auth_frame/auth_frame.dart';
import '../../../../../widgets/instance/instance_builder.dart';
import '../../../../../widgets/loaders/live_data_loader.dart';
import '../widgets/reset_password_form.dart';

class ResetPasswordMobileScreen extends StatefulWidget {
  const ResetPasswordMobileScreen({Key? key}) : super(key: key);

  @override
  State<ResetPasswordMobileScreen> createState() => _ResetPasswordMobileScreenState();
}

class _ResetPasswordMobileScreenState extends State<ResetPasswordMobileScreen> {
  final formKey=GlobalKey<FormState>();


  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ResetPasswordViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return Stack(
              children: [
                AuthFrame(
                  image: "finger-print",
                  title: 'reset_password_info'.tr(),
                  animationType: AnimationType.fadeInUpRight,
                  widget: Form(key:formKey
                      ,child: const ResetPasswordForm()),
                  actionText: 'next',
                  enabled: viewModel.params.submit,
                  action:() {
                    if(formKey.currentState!.validate()){
                      viewModel.resetPassword();

                    }
                  },
                ),
                LoadingListenerWidget(loading: viewModel.baseParams.loading),

              ],
            );
          },
        );
      },
    );

  }
}
