/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';

part 'city.freezed.dart';
part 'city.g.dart';

// ----------(json)----------
/*
{
  "id": 1,
  "created_at": "2023-02-19T07:59:32.000000Z",
  "updated_at": "2023-02-19T07:59:32.000000Z",
  "name": "baramkeh"
}
*/
// --------------------------

@freezed
class City with _$City {
  const factory City({
    int? id,
    String? createdAt,
    String? updatedAt,
    String? name,
  }) = _City;

  factory City.fromJson(Map<String, dynamic> json) => _$CityFromJson(json);
}
