import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/extensions/data_extension.dart';
import 'package:tahsaldar/extensions/formz_extension.dart';
import 'package:tahsaldar/extensions/live_data_extension.dart';
import 'package:tahsaldar/models/data/payment/payment.dart';
import 'package:tahsaldar/models/forms/formz_mobile.dart';
import 'package:tahsaldar/models/forms/formz_text.dart';

/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// declare and manage viewModel-liveData variables.
///
/// see: https://pub.dev/packages/flutterx_live_data
///
/// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e

class AddPaymentParams {
  static late Payment payment;

  /// payer name field
  final payerName = const FormzText.pure("").liveData;

  /// payer mobile mobile text field
  final payerMobile = const FormzMobile.pure().liveData;

  /// payment.json amount
  final paymentAmount = const FormzText.pure("").liveData;

  final amount = (0.0).liveData;
  final fees = (0.0).liveData;
  final totalAmount = (0.0).liveData;
  double feesPercentage = 0.1;

  double get calculateAmount => paymentAmount.inputValue().replaceAll(",", "").toDouble();
  double get calculateFees => calculateAmount * feesPercentage;
  double get calculateTotalAmount => calculateFees + calculateAmount;

  /// note (or reason)
  final note = const FormzText.pure("").liveData;

  /// expiryDate (scheduled to be paid on)
  /// default value is the next day
  final MutableLiveData<DateTime?> expiryDate = MutableLiveData(value: null);

  ///
  final MutableLiveData<DateTime?> scheduledDate = MutableLiveData(value: null);

  /// form enabled for submit
  final submit = false.liveData;

  isFormFilled() {
    return payerName.inputValue().isNotEmpty && payerMobile.value.valid && paymentAmount.inputValue().isNotEmpty && note.inputValue().isNotEmpty;
  }
}
