/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:tahsaldar/extensions/assets_extension.dart';
import 'package:tahsaldar/ui/core/layouts/theme_widget.dart';
import 'package:tahsaldar/ui/resources/colors/colors.dart';

import '../animations/scale_fade_widget.dart';

class OutlinedIconButton extends StatefulWidget {
  final String text;
  final bool enabled;
  final Function() callback;
  final ButtonStyle? style;
  final String svg;
  final Color? color;
  const OutlinedIconButton({
    required this.text,
    required this.callback,
    this.enabled = true,
    this.style,
    required this.svg,
    this.color,
    Key? key,
  }) : super(key: key);

  @override
  State<OutlinedIconButton> createState() => _OutlinedIconButtonState();
}

class _OutlinedIconButtonState extends State<OutlinedIconButton> {
  final GlobalKey<ScaleFadeWidgetState> globalKey = GlobalKey<ScaleFadeWidgetState>();
  final GlobalKey<ScaleFadeWidgetState> childKey = GlobalKey<ScaleFadeWidgetState>();
  @override
  Widget build(BuildContext context) {
    return ThemeWidget(
      builder: (context, theme) {
        return ScaleFadeWidget(
          key: globalKey,
          type: AnimationType.scale,
          scaleValue: 0.015,
          duration: const Duration(milliseconds: 175),
          child: GestureDetector(
            onTap: () async {
              if (!widget.enabled) return;
              globalKey.currentState?.animate();
              childKey.currentState?.animate();
              Future.delayed(const Duration(milliseconds: 300), widget.callback);
            },
            child: Container(
              constraints: BoxConstraints(
                  minHeight: 40
              ),
              padding: const EdgeInsets.symmetric(vertical: 8),
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  color: !widget.enabled ? DesignColors.grey : DesignColors.secondaryBackgroundColor,
                  border: Border.all(color: !widget.enabled ? DesignColors.grey : widget.color ?? DesignColors.primaryColor)),
              child: ScaleFadeWidget(
                duration: const Duration(milliseconds: 200),
                type: AnimationType.fade,
                fadeValue: 0.5,
                key: childKey,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    SvgPicture.asset(widget.svg.svgAsset, color: !widget.enabled ? Colors.white : widget.color ?? DesignColors.primaryColor, height: 24),
                    const SizedBox(width: 4),
                    Text(
                      widget.text.tr(),
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w400,
                        color: !widget.enabled ? Colors.white : widget.color ?? DesignColors.primaryColor,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}
