/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/resources/colors/colors.dart';
import 'package:tahsaldar/ui/resources/text_styles/text_styles.dart';

void showSnackBar({
  required BuildContext context,
  required String message,
  Function()? callback,
  TextStyle? textStyle,
  String? action,
  Color? backgroundColor,
}) {
  ScaffoldMessenger.of(context)
    ..hideCurrentSnackBar()
    ..showSnackBar(
      SnackBar(
        behavior: SnackBarBehavior.floating,
        content: Text(message,
            style: body3.copyWith(
              color: DesignColors.textColor,
            )),
        backgroundColor: DesignColors.purple3,
        action: SnackBarAction(
          label: action ?? "Ok",
          textColor: DesignColors.textColor,
          onPressed: () {
            callback?.call();
          },
        ),
      ),
    );
}
