/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';

class DesignColors {
  static const Color primaryColor = Color(0xFF5903E9);
  static const Color secondaryColor = Color(0xFFFF653A);
  static const Color errorColor = Colors.red;
  static const Color secondaryBackgroundColor = Color(0xFFFFFFFF);
  static const Color grey = Color(0xFFC7C7D2);
  static const Color textColor = Color(0xFF0E0E0E);

  static const Color purple2 = Color(0xFF7C30FA);
  static const Color purple3 = Color(0xFFF2EBFE);
  static const Color purple4 = Color(0xFFF9F5FF);
}
