/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import "./viewmodels/complete_info_viewmodel.dart";
import '../../core/layouts/base_app_bar.dart';
import 'mobile/complete_info_mobile_screen.dart';

class CompleteInfoScreen extends StatefulWidget {
  const CompleteInfoScreen({Key? key}) : super(key: key);

  @override
  State<CompleteInfoScreen> createState() => _CompleteInfoScreenState();
}

class _CompleteInfoScreenState extends State<CompleteInfoScreen> with InstanceState<CompleteInfoScreen, CompleteInfoViewModel>, ObserverMixin {
  @override
  void observeLiveData(lifeCycle, viewModel) {
    // register observers...
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(),
          builder: (context, theme) {
            return const ScreenTypeLayout(mobile: CompleteInfoMobileScreen());
          },
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  CompleteInfoViewModel registerInstance() => CompleteInfoViewModel();
}
