/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';

part 'bank.freezed.dart';
part 'bank.g.dart';

// ----------(json)----------
/*
{
  "id": 1,
  "created_at": "2023-02-19T07:59:32.000000Z",
  "updated_at": "2023-02-19T07:59:32.000000Z",
  "name": "al baraka"
}
*/
// --------------------------

@freezed
class Bank with _$Bank {
  const factory Bank({
    int? id,
    String? createdAt,
    String? updatedAt,
    String? name,
  }) = _Bank;

  factory Bank.fromJson(Map<String, dynamic> json) => _$BankFromJson(json);
}
