/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
/// 
/// state management for UI
/// 
/// store and manage your liveData in [LoginPasswordParams].
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/extensions/formz_extension.dart';

import '../../../../controllers/auth_controller.dart';
import '../../../../models/forms/formz_text.dart';
import '../../../../repositories/user_repository.dart';
import '../../../../router/app_router.dart';
import "login_password_params.dart";
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:tahsaldar/viewmodels/base_viewmodel.dart';

class LoginPasswordViewModel extends BaseViewModel { 
  final _params = Lazy(() => LoginPasswordParams());
  LoginPasswordParams get params => _params.value;

  final _userRepository = Lazy(() => UserRepository());
  UserRepository get userRepository => _userRepository.value;

  void attrChanged(MutableLiveData<FormzText> attr, String value) {
    final newValue = FormzText.dirty(value);
    attr.postValue(newValue);
    params.submit.postValue(params.password.inputValue().length>=6);
  }
  loginPassword() {
    String mobile = params.mobile;
    String password = params.password.inputValue();
    callHttpRequest(
          () => userRepository.loginPassword(mobile, password),
      loading: baseParams.loading,
      callback: (response) async {
        if (response != null && response.user != null) {
          await AuthenticationController.login(response.user!);
            appRouter.replaceAll([const Main()]);

        }
      },
    );
  }

}
