/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/core/layouts/theme_widget.dart';
import 'package:tahsaldar/ui/widgets/animations/animated_column.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";

import '../../../resources/dimensions/dimensions.dart';
import "../viewmodels/settings_viewmodel.dart";
import '../widgets/about_us.dart';
import '../widgets/contact_us.dart';
import '../widgets/language_setting.dart';
import '../widgets/notification_setting.dart';
import '../widgets/settings_card.dart';

class SettingsMobileScreen extends StatelessWidget {
  const SettingsMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<SettingsViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return Padding(
              padding: const EdgeInsets.fromLTRB(16, spaceBelowAppBar, 16, 0),
              child: AnimatedColumn(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Column(
                    children: [
                      SettingsCard(
                        height: 130,
                        child: LanguageSetting(
                          liveData: viewModel.params.preferredLanguage,
                        ),
                      ),
                      const SizedBox(height: 16),
                      const SettingsCard(
                        child: NotificationSetting(),
                      ),
                      const SizedBox(height: 16),
                      const SettingsCard(
                        child: AboutUs(),
                      ),
                    ],
                  ),
                  const ContactUs(),
                ],
              ),
            );
          },
        );
      },
    );
  }
}
