name: notifications
description: Package to configuration Notifications
version: 1.0.0
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.6.1
  flutter_local_notifications: 13.0.0
  firebase_messaging: 14.2.4
  fluttertoast: ^8.1.4
  http: ^0.13.5
  firebase_core_platform_interface: 4.5.3

dev_dependencies:
  lints: ^2.0.0
