/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';
part 'setting.freezed.dart';
part 'setting.g.dart';

// ----------(json)----------
/*
{
  "id": 1,
  "key": "fees_percentage",
  "value": "10",
  "created_at": "2023-06-11T09:30:01.000000Z",
  "updated_at": "2023-06-11T09:30:01.000000Z"
} 
*/
// --------------------------

@freezed
class Setting with _$Setting {
  const factory Setting({
    int? id,
    String? key,
    dynamic value,
    String? createdAt,
    String? updatedAt,
  }) = _Setting;

  factory Setting.fromJson(Map<String, dynamic> json) => _$SettingFromJson(json);
}
