/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import "package:easy_localization/easy_localization.dart";
import 'package:flutter/material.dart';
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";
import "../../../core/layouts/theme_widget.dart";
import "../../../shared/auth_frame/auth_frame.dart";
import "../viewmodels/login_password_viewmodel.dart";
import "../widgets/login_password_form.dart";


class LoginPasswordMobileScreen extends StatelessWidget {
  const LoginPasswordMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<LoginPasswordViewModel>(
    builder: (viewModel) {
      return ThemeWidget(
        builder: (context, theme) {
          return AuthFrame(
            image: 'verify-code',
            animationType: AnimationType.fadeInRight,
            title: 'welcome_q_pay'.tr(),
            widget: const LoginPasswordForm(),
            actionText: 'next',
            enabled: viewModel.params.submit,
            action: viewModel.loginPassword,
          );
        },
      );
    },
    );
  }
}
