/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// state management for UI
///
/// store and manage your liveData in [MainParams].
import 'dart:io';

import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:tahsaldar/repositories/user_repository.dart';
import 'package:tahsaldar/storage/storage.dart';
import 'package:tahsaldar/viewmodels/base_viewmodel.dart';

import '../../../../notifications/notification_handler.dart';
import "main_params.dart";

class MainViewModel extends BaseViewModel {
  final _params = Lazy(() => MainParams());
  MainParams get params => _params.value;

  final _userRepository = Lazy(() => UserRepository());
  UserRepository get userRepository => _userRepository.value;

  @override
  void onInit() {
    super.onInit();
    updateFcmToken();
  }

  @override
  void onDispose() {
    userRepository.dispose();
    super.onDispose();
  }

  /// update fcm token either s
  /// end to server and save it in local storage. (if notifications not muted)
  /// or remove fcm token from server if notifications muted
  Future updateFcmToken() async {
    final token = await notificationService.getMessagingToken();
    bool receiveNotifications = await AppStorage.getNotificationReceivingStatus();
    if (token != null && receiveNotifications) {
      AppStorage.setFcmToken(token);
      userRepository.setFcmToken(token, Platform.isIOS ? 'ios' : 'android');
    } else {
      userRepository.removeFcmToken();
    }
  }
}
