/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import "./viewmodels/verify_code_viewmodel.dart";
import '../../core/layouts/base_app_bar.dart';
import 'mobile/verify_code_mobile_screen.dart';

class VerifyCodeScreen extends StatefulWidget {
  final String mobile;
  const VerifyCodeScreen({required this.mobile, Key? key}) : super(key: key);

  @override
  State<VerifyCodeScreen> createState() => _VerifyCodeScreenState();
}

class _VerifyCodeScreenState extends State<VerifyCodeScreen> with InstanceState<VerifyCodeScreen, VerifyCodeViewModel>, ObserverMixin {
  @override
  void onInitState(VerifyCodeViewModel instance) {
    super.onInitState(instance);
    instance.params.mobile = widget.mobile;
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(),
          builder: (context, theme) {
            return const ScreenTypeLayout(mobile: VerifyCodeMobileScreen());
          },
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  VerifyCodeViewModel registerInstance() => VerifyCodeViewModel();
}
