/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:tahsaldar/ui/screens/add_payment/add_payment_screen.dart';
import 'package:tahsaldar/ui/screens/complete_info/complete_info_screen.dart';
import 'package:tahsaldar/ui/screens/image_cropper/image_cropper_screen.dart';
import 'package:tahsaldar/ui/screens/initial/initial_screen.dart';
import 'package:tahsaldar/ui/screens/login/login_screen.dart';
import 'package:tahsaldar/ui/screens/main/main_screen.dart';
import 'package:tahsaldar/ui/screens/notifications/notifications_screen.dart';
import 'package:tahsaldar/ui/screens/profile/profile_screen.dart';
import 'package:tahsaldar/ui/screens/settings/settings_screen.dart';
import 'package:tahsaldar/ui/screens/transactions/transactions_screen.dart';
import 'package:tahsaldar/ui/screens/transactions_details/transactions_details_screen.dart';
import 'package:tahsaldar/ui/screens/update_profile/update_profile_screen.dart';
import 'package:tahsaldar/ui/screens/verify_code/verify_code_screen.dart';

import '../models/data/payment/payment.dart';

part 'app_router.gr.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    AutoRoute(path: '/image_cropper', page: ImageCropperScreen, name: 'ImageCropper'),
    AutoRoute(path: '/update_profile', page: UpdateProfileScreen, name: 'UpdateProfile'),
    AutoRoute(path: '/add_payment', page: AddPaymentScreen, name: 'AddPayment'),
    AutoRoute(path: '/settings', page: SettingsScreen, name: 'Settings'),
    AutoRoute(path: '/notifications', page: NotificationsScreen, name: 'Notifications'),
    AutoRoute(path: '/transactions_details', page: TransactionsDetailsScreen, name: 'TransactionsDetails'),
    AutoRoute(path: '/profile', page: ProfileScreen, name: 'Profile'),
    AutoRoute(path: '/transactions', page: TransactionsScreen, name: 'Transactions'),
    AutoRoute(path: '/main', page: MainScreen, name: 'Main'),
    AutoRoute(path: '/complete_info', page: CompleteInfoScreen, name: 'CompleteInfo'),
    AutoRoute(path: '/verify_code', page: VerifyCodeScreen, name: 'VerifyCode'),
    AutoRoute(path: '/login', page: LoginScreen, name: 'Login'),
    AutoRoute(path: '/initial', page: InitialScreen, name: 'Initial', initial: true),
  ],
)
// extend the generated private router
class AppRouter extends _$AppRouter {}

final appRouter = AppRouter();
