/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import "package:easy_localization/easy_localization.dart";
import 'package:flutter/material.dart';
import "package:flutter_svg/svg.dart";
import "package:flutterx_live_data/flutterx_live_data.dart";
import "package:tahsaldar/extensions/assets_extension.dart";
import "package:tahsaldar/ui/screens/transfer_details/transfer_details_screen.dart";
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";
import "../../../../models/data/payment/payment.dart";
import "../../../../models/data/total_paid/total_paid.dart";
import "../../../../router/app_router.dart";
import "../../../core/layouts/theme_widget.dart";
import "../../../resources/colors/colors.dart";
import "../../../resources/dimensions/dimensions.dart";
import "../../../resources/text_styles/text_styles.dart";
import "../../../shared/empty_view.dart";
import "../../../shared/total_amount/total_amount_card.dart";
import "../../../widgets/buttons/customized_button.dart";
import "../../../widgets/infinite_scroll_view/infinite_scroll_view.dart";
import "../viewmodels/transfers_viewmodel.dart";
import "../widgets/transfer_card.dart";


class TransfersMobileScreen extends StatelessWidget {
  const TransfersMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<TransfersViewModel>(
      builder: (viewModel) {
        return SafeArea(
          child: ThemeWidget(
            builder: (context, theme) {
              return Column(
                children: [
                  ///list of transactions
                   Expanded(
                    child: LiveDataBuilder<bool>(
                      data: viewModel.params.zeroTransfer,
                      builder: (context, isEmpty) {
                        return isEmpty
                            ? Column(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Padding(
                              padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
                              child: LiveDataBuilder<TotalPaid>(
                                data: viewModel.params.totalPaid,
                                builder: (context, totalPaid) => TotalAmountCard(
                                  isTransfer: true,
                                  month: viewModel.params.month,
                                  year: viewModel.params.year,
                                  totalPaid: totalPaid,
                                  filter: viewModel.getTotalPaid,
                                ),
                              ),
                            ),
                            EmptyView(message: 'no_transfer_yet'.tr()),
                            const SizedBox(),
                          ],
                        )
                            : InfiniteScrollView<TransfersViewModel, Payment>(
                          physics: const ClampingScrollPhysics(),
                             topWidget: Column(
                               children: [
                                 Padding(
                                   padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
                                   child: LiveDataBuilder<TotalPaid>(
                                     data: viewModel.params.totalPaid,
                                     builder: (context, totalPaid) => TotalAmountCard(
                                       isTransfer: true,
                                       month: viewModel.params.month,
                                       year: viewModel.params.year,
                                       totalPaid: totalPaid,
                                       filter: viewModel.getTotalPaid,
                                     ),
                                   ),
                                 ),
                                 Padding(
                                   padding: const EdgeInsets.fromLTRB(14, 16, 24, 12),
                                   child: Row(
                                     children: [
                                       SvgPicture.asset('empty-wallet'.svgAsset, color: DesignColors.primaryColor),
                                       const SizedBox(width: 4),
                                       Text('last_transfer'.tr(), style: title2),
                                     ],
                                   ),
                                 ),
                               ],
                             ),
                          loaderColor: DesignColors.secondaryBackgroundColor,
                          viewModel: viewModel,
                          itemBuilder: (transfer) => Padding(
                            padding:  const EdgeInsets.symmetric(horizontal: twoUnits),
                            child: InkWell(
                              onTap: () => appRouter.push(TransferDetails(transfer: transfer)),
                              child: TransferCard(
                                transfer: transfer,
                              ),
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                  Container(
                    padding:  const EdgeInsets.symmetric(horizontal: twoUnits,vertical:halfUnit ),
                    width: double.infinity,
                    child: CustomizedButton(
                      text: "add_transfer_request",
                      icon: const Icon(Icons.add_box_outlined, color: Colors.white),
                      callback: () async {
                        final result = await appRouter.push(const AddTransfer());
                        if (result != null) {
                          viewModel
                            ..refresh()
                            ..clear()
                            ..getTotalPaid()
                            ..getPaginationList();
                        }
                      },
                    ),
                  )
                ],
              );
            },
          ),
        );
      },
    );
  }
}
