/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";

import "./viewmodels/notifications_viewmodel.dart";
import '../../core/layouts/base_app_bar.dart';
import 'mobile/notifications_mobile_screen.dart';

class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({Key? key}) : super(key: key);

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> with InstanceState<NotificationsScreen, NotificationsViewModel>, ObserverMixin {
  @override
  void observeLiveData(lifeCycle, viewModel) {
    // register observers...
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return BaseScaffold(
      appBar: (context, theme) => baseAppBar(
        title: 'notifications'.tr(),
      ),
      builder: (context, theme) => const ScreenTypeLayout(
        mobile: NotificationsMobileScreen(),
      ),
    );
  }

  @override
  NotificationsViewModel registerInstance() => NotificationsViewModel();
}
