/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tahsaldar/network/config/env.dart';

import '../customer/customer.dart';

part 'payment.freezed.dart';
part 'payment.g.dart';

// ----------(json)----------
/*
{
  "id": 1,
  "payer_name": "Mohammad",
  "payer_mobile_number": "0993522958",
  "amount": 50000,
  "details": "Debt on him",
  "status": 1,
  "expiry_date": "2023-10-10",
  "paid_at": null,
  "user_id": 1,
  "created_at": "2023-02-19T11:20:19.000000Z",
  "updated_at": "2023-02-19T11:20:19.000000Z"
}
*/
// --------------------------

@freezed
class Payment with _$Payment {
  const factory Payment({
    int? id,
    String? payerName,
    String? payerMobileNumber,
    Customer? customer,
    num? amount,
    num? feesValue,
    String? details,
    int? status,
    DateTime? expiryDate,
    DateTime? scheduledDate,
    DateTime? paidAt,
    int? userId,
    String? uuid,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) = _Payment;

  factory Payment.fromJson(Map<String, dynamic> json) => _$PaymentFromJson(json);
}

//PENDING = 1;
//SCHEDULED = 2;
//PAID = 3;
//EXPIRED = 4;
//CANCELLED = 5;
//REFUNDED = 6
Map<int, String> transactionStatuses = {1: 'pending', 2: 'scheduled', 3: 'paid', 4: 'expired', 5: 'canceled', 6: 'refunded',7:'settled'};

extension PaymentExtensions on Payment {
  //todo check refunded status number
  bool isNotDeletable() => status is int &&  (status as int) > 3;

  String get link => "${Env.baseUrl}/payForm/$uuid";
}
