/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import '../../../../core/layouts/base_app_bar.dart';
import '../../../../widgets/instance/instance_state.dart';
import '../../viewmodels/reset_password_viewmodel.dart';
import 'mobile/reset_password_verification_mobile_screen.dart';

class ResetPasswordVerificationScreen extends StatefulWidget {
  final String mobile;

  const ResetPasswordVerificationScreen({Key? key, required this.mobile})
      : super(key: key);

  @override
  State<ResetPasswordVerificationScreen> createState() =>
      _ResetPasswordVerificationScreenState();
}

class _ResetPasswordVerificationScreenState
    extends State<ResetPasswordVerificationScreen>
    with
        InstanceState<ResetPasswordVerificationScreen, ResetPasswordViewModel>,
        ObserverMixin {
  @override
  void onInitState(ResetPasswordViewModel instance) {

    super.onInitState(instance);
    instance.params.phone = widget.mobile;
    instance.resetPasswordRequest();

  }

  @override
  Widget screen(BuildContext context, ResetPasswordViewModel instance) {
    return BaseScaffold(
      appBar: (context, theme) => baseAppBar(title: "reset_password".tr()),
      builder: (context, theme) => const ScreenTypeLayout(
          mobile: ResetPasswordVerificationMobileScreen()),
    );
  }

  @override
  ResetPasswordViewModel registerInstance() => ResetPasswordViewModel();
}
