/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import "package:tahsaldar/ui/screens/add_transfer/widgets/add_transfer_form.dart";
import "package:tahsaldar/ui/widgets/instance/instance_builder.dart";
import "../../../core/layouts/theme_widget.dart";
import "../../../resources/dimensions/dimensions.dart";
import "../viewmodels/add_transfer_viewmodel.dart";


class AddTransferMobileScreen extends StatelessWidget {
  const AddTransferMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<AddTransferViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return  Padding(
              padding: const EdgeInsets.only(top: spaceBelowAppBar),
              child: AddTransferForm(),
            );
          },
        );
      },
    );
  }
}
