/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:tahsaldar/ui/core/layouts/base_app_bar.dart';
import 'package:tahsaldar/ui/core/layouts/base_scaffold.dart';
import 'package:tahsaldar/ui/core/responsive/screen_type_layout.dart';
import "package:tahsaldar/ui/widgets/instance/instance_state.dart";
import 'package:tahsaldar/ui/widgets/loaders/live_data_loader.dart';

import 'viewmodels/settings_viewmodel.dart';
import 'mobile/settings_mobile_screen.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({Key? key}) : super(key: key);

  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> with InstanceState<SettingsScreen, SettingsViewModel>, ObserverMixin {
  @override
  void observeLiveData(lifeCycle, viewModel) {
    // register observers...
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => baseAppBar(title: "settings".tr()),
          builder: (context, theme) {
            return const ScreenTypeLayout(mobile: SettingsMobileScreen());
          },
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  SettingsViewModel registerInstance() => SettingsViewModel();
}
